[package]
name = "auth-middleware-for-actix-web"
authors = ["Stefan Simon <stefan.j.c.simon@gmail.com>"]
keywords = ["actix", "actix-web", "middleware", "auth", "authentication", "session", "web"]
exclude = [".gitignore"]
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web="4"
log = "0.4.21"
serde = { version = "1.0.216", features = ["derive"]}
actix-session = "0.10.1"
futures = "0.3.31"
regex = "1.11.1"
urlencoding = "2.1.3"
thiserror = "2.0.11"

# feature: google_auth
google-authenticator = { version = "0.4.2", optional = true }
qrcode-generator = { version = "5.0.0", optional = true }
rand = { version = "0.9.0", optional = true }
base32 = { version = "0.5.1", optional = true }

[dev-dependencies]
reqwest = { version = "0.12.11", features = ["cookies"]}
actix-session = { version = "0.10.1", features = ["cookie-session"]}
actix-rt = "2.10.0"
actix-test = "0.1.5"

# to make integration tests work
auth-middleware-for-actix-web = { path = ".", features = ["google_auth"] } 

[features]
google_auth = ["dep:google-authenticator", "dep:qrcode-generator", "dep:rand", "dep:base32"]